### ISSUE TITLE
Misc. errata in STR IG/slides I noticed in studying the material

### ISSUE THREAD

**Issue by doughogan** [confluentinc/training-ksql-and-streams-src#26]
- [x] Timing Tables for Day 2 and Day 3 have the “Using the KSQL REST API” module misplaced compared to where it is placed in reality. All number from Module 8 on is inaccurate.
- [ ] 09-08 - Please add arrowheads like in DEV
- [x] 09-21 - Should “semantic” be “semantics” in the bulleted list?
- [ ] 09-21 - Might be nice to list `processing.guarantee` and its values on the slide. 
- [x] 11-14: Is it GlobalKTable or KGlobalTable? IG text vs. slide text vary. Same on next slide.

**Comment by dhbrenner** [comment]
These are primarily complete (not moving processing guarantees to the slide)
Also, wrong repo - s/b in training-ksql-and-streams
