### ISSUE TITLE
More misc errata from my reading the last of the slides

### ISSUE THREAD

**Issue by doughogan** [confluentinc/training-ksql-and-streams-src#27]
- [ ] 12-3, IG box, third paragraph: “distinguish” missing ‘h’

- [ ] 13-6, IG box, third bullet: seems to have something odd going with a missing character and parsing at the end. 

- [ ] In general, there are some good discussion questions at the end of modules. Could we get sample responses added for all of them - and/or what the takeaways ought to be - to help trainers ramping on the course? (This is in some, but not all, modules.)

**Comment by dhbrenner** [comment]
wrong repo - s/b in training-ksql-and-streams not training-ksql-and-streams-src but also appear to have been corrected in training-ksql-and-streams
