### ISSUE TITLE
11-14 - KGlobalTable vs. GlobalKTable

### ISSUE THREAD

**Issue by doughogan** [confluentinc/training-ksql-and-streams-src#28]
"KGlobalTable" appears in the IG box of 11-20, third bullet. when it should be "GlobalKTable." It also appears as the last bullet; could these be combined?

Third bullet is missing the 'r' in "underlying."

**Comment by dhbrenner** [comment]
both of these issues have been corrected - no longer exist at 5,5,0-v1.0.0
