### ISSUE TITLE
update kafka properties in docker-compose files to speed up ksql queries

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/training-ksql-and-streams-src#4]
in the various docker-compose files you can dd this line `     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100` to reduce the initial delay you see when launching a KSQL query, this makes the whole thing _feel_ much faster. (the default value, iirc, is 3000)

What it really means: it's the amount of time the broker will wait for any other members of the consuming application to join the consumer group (there's one consumer group per ksql query) before assigning partitions to group members and starting to serve data. In any kind of single-broker, single-ksql environment - like a class or a demo! - you don't have to wait because you know there will only ever be one group member.

**Comment by gnschenker** [comment]
This is a property on the broker!

**Comment by blueedgenick** [comment]
Yes! :-). It has the effect of delaying the initial send of messages to any
new consumer group, not only those created for ksql queries.

**Comment by gnschenker** [comment]
fixed in PR #17
